<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PresentationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('presentations')->delete();
        
        \DB::table('presentations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'POMADA',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 16:24:47',
                'updated_at' => '2025-10-20 22:17:27',
                'registerUser_id' => NULL,
                'registerRole' => NULL,
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'GOTAS',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:16:34',
                'updated_at' => '2025-10-20 22:17:00',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'COMPRIMIDOS',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:18:06',
                'updated_at' => '2025-10-20 22:18:06',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'TABLETAS',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:18:30',
                'updated_at' => '2025-10-20 22:18:30',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'LOCION',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:18:42',
                'updated_at' => '2025-10-20 22:18:42',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'BOLSA',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:19:04',
                'updated_at' => '2025-10-20 22:19:04',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'TABLETA',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:19:09',
                'updated_at' => '2025-10-20 22:19:09',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'CAPSULAS',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:19:19',
                'updated_at' => '2025-10-20 22:19:19',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'PASTA',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:19:30',
                'updated_at' => '2025-10-20 22:19:30',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'JARABE',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:19:37',
                'updated_at' => '2025-10-20 22:26:42',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'OVULOS',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:19:44',
                'updated_at' => '2025-10-20 22:19:44',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'VIAL',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:19:53',
                'updated_at' => '2025-10-20 22:19:53',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'AMPOLLA',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:20:01',
                'updated_at' => '2025-10-20 22:20:01',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'PARCHE',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:20:11',
                'updated_at' => '2025-10-20 22:20:11',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'PIEZA',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:20:17',
                'updated_at' => '2025-10-20 22:20:17',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'FRASCO',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:20:28',
                'updated_at' => '2025-10-20 22:20:28',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'SOLUCION',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:20:36',
                'updated_at' => '2025-10-20 22:20:36',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'SOBRE',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:20:52',
                'updated_at' => '2025-10-20 22:20:52',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'SUSPENSION',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:21:01',
                'updated_at' => '2025-10-20 22:21:01',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'AEROSOL',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:21:06',
                'updated_at' => '2025-10-20 22:21:06',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'GEL',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:21:15',
                'updated_at' => '2025-10-20 22:21:15',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'POLVO',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:26:07',
                'updated_at' => '2025-10-20 22:26:07',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'SUPOSITORIOS',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:26:13',
                'updated_at' => '2025-10-20 22:26:13',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'PASTILLAS',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:26:57',
                'updated_at' => '2025-10-20 22:26:57',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'CREMA',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:27:22',
                'updated_at' => '2025-10-20 22:27:22',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'LABIAL',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:27:34',
                'updated_at' => '2025-10-20 22:27:34',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'PAÑUELOS',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:27:51',
                'updated_at' => '2025-10-20 22:27:51',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'ALGODÓN',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:28:08',
                'updated_at' => '2025-10-20 22:28:08',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'LUBRICANTE',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:28:19',
                'updated_at' => '2025-10-20 22:28:19',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'OLEO',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:28:29',
                'updated_at' => '2025-10-20 22:28:29',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'PESONES',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:28:42',
                'updated_at' => '2025-10-20 22:28:42',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'CAJA',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:29:40',
                'updated_at' => '2025-10-20 22:29:40',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'EMULSION',
                'observation' => NULL,
                'status' => 1,
                'created_at' => '2025-10-20 22:29:52',
                'updated_at' => '2025-10-20 22:29:52',
                'registerUser_id' => 1,
                'registerRole' => 'admin',
                'deleted_at' => NULL,
                'deleteUser_id' => NULL,
                'deleteRole' => NULL,
                'deleteObservation' => NULL,
            ),
        ));
        
        
    }
}